install: 
    - cinst -y pester
    - git clone https://github.com/PowerShell/DscResource.Tests
    - ps: winrm quickconfig -quiet  
    - ps: test-wsman  
    - ps: $env:PsModulePath  
    - ps: Get-ChildItem "C:\Program Files\WindowsPowerShell\Modules"
    - ps: Get-ChildItem C:\projects
    - ps: Get-ChildItem C:\projects -include xPSDesiredStateConfiguration -Recurse | copy-item -Destination "C:\Program Files\WindowsPowerShell\Modules" -Recurse -force 
    - ps: Get-ChildItem "C:\Program Files\WindowsPowerShell\Modules"

build: false

test_script:
    - ps: |
        $testResultsFile = ".\TestsResults.xml"
        $tempModulePath = (Resolve-Path (join-path $PWD '..')).ProviderPath
        $env:PSModulePath = "$env:PSModulePath;$tempModulePath"        
        $res = Invoke-Pester -OutputFormat NUnitXml -OutputFile $testResultsFile -PassThru
        (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))
        if ($res.FailedCount -gt 0) { 
            throw "$($res.FailedCount) tests failed."
        }
on_finish:
    - ps: |
        $stagingDirectory = (Resolve-Path ..).Path
        $zipFile = Join-Path $stagingDirectory "$(Split-Path $pwd -Leaf).zip"
        Add-Type -assemblyname System.IO.Compression.FileSystem
        [System.IO.Compression.ZipFile]::CreateFromDirectory($pwd, $zipFile)
        @(
            # You can add other artifacts here
            (ls $zipFile)
        ) | % { Push-AppveyorArtifact $_.FullName }

